[2025-02-20T17:23:48.388+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T17:23:48.407+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_v1.get_raw_data manual__2025-02-20T15:48:20.200082+00:00 [queued]>
[2025-02-20T17:23:48.416+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_v1.get_raw_data manual__2025-02-20T15:48:20.200082+00:00 [queued]>
[2025-02-20T17:23:48.417+0000] {taskinstance.py:2867} INFO - Starting attempt 11 of 11
[2025-02-20T17:23:48.587+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_raw_data> on 2025-02-20 15:48:20.200082+00:00
[2025-02-20T17:23:48.597+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=355) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-20T17:23:48.598+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_v1', 'get_raw_data', 'manual__2025-02-20T15:48:20.200082+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_v1.py', '--cfg-path', '/tmp/tmpn6uv1aec']
[2025-02-20T17:23:48.599+0000] {standard_task_runner.py:72} INFO - Started process 364 to run task
[2025-02-20T17:23:48.599+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask get_raw_data
[2025-02-20T17:23:48.652+0000] {task_command.py:467} INFO - Running <TaskInstance: recalls_etl_v1.get_raw_data manual__2025-02-20T15:48:20.200082+00:00 [running]> on host a50f66475725
[2025-02-20T17:23:48.736+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_v1' AIRFLOW_CTX_TASK_ID='get_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T15:48:20.200082+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T15:48:20.200082+00:00'
[2025-02-20T17:23:48.738+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-20T17:23:48.739+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-20T17:23:48.739+0000] {logging_mixin.py:190} INFO - Current task name:get_raw_data state:running start_date:2025-02-20 17:23:48.408113+00:00
[2025-02-20T17:23:48.740+0000] {logging_mixin.py:190} INFO - Dag name:recalls_etl_v1 and current dag run status:running
[2025-02-20T17:23:48.740+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T17:23:51.293+0000] {logging_mixin.py:190} INFO - <Response [200]>
[2025-02-20T17:23:51.315+0000] {logging_mixin.py:190} INFO - Added 31655 recalled records.
[2025-02-20T17:23:51.506+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-20T17:23:51.518+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T17:23:51.518+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=recalls_etl_v1, task_id=get_raw_data, run_id=manual__2025-02-20T15:48:20.200082+00:00, execution_date=20250220T154820, start_date=20250220T172348, end_date=20250220T172351
[2025-02-20T17:23:51.542+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-20T17:23:51.543+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-20T17:23:51.543+0000] {logging_mixin.py:190} INFO - Dag name:recalls_etl_v1 queued_at:2025-02-20 17:23:46.591200+00:00
[2025-02-20T17:23:51.544+0000] {logging_mixin.py:190} INFO - Task hostname:a50f66475725 operator:PythonOperator
[2025-02-20T17:23:51.585+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-20T17:23:51.616+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-20T17:23:51.618+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
