[2025-02-20T17:25:41.502+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-20T17:25:41.526+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_v1.load_data_to_db manual__2025-02-20T15:48:20.200082+00:00 [queued]>
[2025-02-20T17:25:41.537+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_v1.load_data_to_db manual__2025-02-20T15:48:20.200082+00:00 [queued]>
[2025-02-20T17:25:41.539+0000] {taskinstance.py:2867} INFO - Starting attempt 6 of 6
[2025-02-20T17:25:41.722+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): load_data_to_db> on 2025-02-20 15:48:20.200082+00:00
[2025-02-20T17:25:41.732+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=403) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-20T17:25:41.734+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_v1', 'load_data_to_db', 'manual__2025-02-20T15:48:20.200082+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_v1.py', '--cfg-path', '/tmp/tmpnlkt3qli']
[2025-02-20T17:25:41.738+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask load_data_to_db
[2025-02-20T17:25:41.738+0000] {standard_task_runner.py:72} INFO - Started process 405 to run task
[2025-02-20T17:25:41.793+0000] {task_command.py:467} INFO - Running <TaskInstance: recalls_etl_v1.load_data_to_db manual__2025-02-20T15:48:20.200082+00:00 [running]> on host a50f66475725
[2025-02-20T17:25:41.885+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_v1' AIRFLOW_CTX_TASK_ID='load_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2025-02-20T15:48:20.200082+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-20T15:48:20.200082+00:00'
[2025-02-20T17:25:41.887+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-20T17:25:41.887+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-20T17:25:41.888+0000] {logging_mixin.py:190} INFO - Current task name:load_data_to_db state:running start_date:2025-02-20 17:25:41.526747+00:00
[2025-02-20T17:25:41.888+0000] {logging_mixin.py:190} INFO - Dag name:recalls_etl_v1 and current dag run status:running
[2025-02-20T17:25:41.888+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-20T17:25:43.272+0000] {logging_mixin.py:190} INFO - Success: Loaded 31655 recall records to recalls_db.
[2025-02-20T17:25:43.275+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-20T17:25:43.293+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-20T17:25:43.294+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=recalls_etl_v1, task_id=load_data_to_db, run_id=manual__2025-02-20T15:48:20.200082+00:00, execution_date=20250220T154820, start_date=20250220T172541, end_date=20250220T172543
[2025-02-20T17:25:43.322+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-20T17:25:43.322+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-20T17:25:43.323+0000] {logging_mixin.py:190} INFO - Dag name:recalls_etl_v1 queued_at:2025-02-20 17:25:32.841174+00:00
[2025-02-20T17:25:43.323+0000] {logging_mixin.py:190} INFO - Task hostname:a50f66475725 operator:PythonOperator
[2025-02-20T17:25:43.359+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-20T17:25:43.384+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-20T17:25:43.387+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
